### ISSUE TITLE
Missing last step for compiling RouteOPT

### ISSUE THREAD

**Issue by danieloliveira56** [Zhengzhong-You/RouteOpt#2]
Hello, thanks for this awesome project. The instructions for compiling are very good. But maybe adding the last step for building CVRP can help unexperience users.

```
cd Application/CVRP/CVRP
mkdir build && cd build
cmake ..
make
```

And I believe there's some typo around here that's making the command not display properly.
![image](https://github.com/Zhengzhong-You/RouteOpt/assets/5332622/39057ead-b4a1-436e-a683-fad3356b380f)

**Comment by Zhengzhong-You** [comment]
Apologies for the earlier display issue, which has now been resolved. Additionally, the user manual has been updated with more detailed instructions for usage. I am currently working on further developing this project and plan to release a more advanced version within March. Please look forward to it, and thank you for your contribution to the project.

**Comment by Zhengzhong-You** [comment]
The standard way of building the source is definitely your style, building from the 'build' directory. I will update the step later since I build the source at 'Application/CVRP/CVRP' directly for convenience and thus the relative paths for 'instances' will need to be changed accordingly. I plan to make this change during the next round of updates for RouteOpt. Thank you for your suggestion.
